apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb 
  labels:
    app: simpleweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb 
    spec:
      containers:
        - name: simpleweb
          image: harbor.default.svc.cluster.local/ogcio/simple-web:1.0
          ports:
            - containerPort: 80
